language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-all-dev

before_script:
  - cmake -G"Unix Makefiles"
  - touch configure
  - chmod +x configure

notifications:
email: false
