language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - cmake
    - libboost-all-dev

before_install:
  - mkdir ~/cmake_tmp
  - cd ~/cmake_tmp
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz -O cmake3.tar.gz
  - tar xf cmake3.tar.gz -C . --strip-components=1
  - export PATH=~/cmake_tmp/bin:$PATH
  - cd -

before_script:
  - cmake -G"Unix Makefiles"
  - touch configure
  - chmod +x configure

notifications:
email: false
